name: Test

on:
  push:
    branches: [ master , dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install swi-prolog
      shell: PowerShell
      run: |
        cd C:\
        curl.exe -k -L "https://drive.google.com/uc?id=1bYQPiHN3_T8DoWYsdpeK0NsKrHzlCxcJ" --output swipl.zip
        Expand-Archive -Force .\swipl.zip C:\
        echo "C:\swipl\bin" >> $GITHUB_PATH

    - name: Checkout submodules
      shell: cmd
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Test
      shell: cmd
      run: make test

    - name: Zip
      shell: cmd
      run: make zip

    - name: Upload zip
      uses: actions/upload-artifact@v2
      with:
        name: PLOG_TP1_RI_T2_Glaisher4.zip
        path: PLOG_TP1_RI_T2_Glaisher4.zip
