name: Test

on:
  push:
    branches: [ master , dev , loads ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install swi-prolog
      run: |
        sudo apt-add-repository ppa:swi-prolog/stable
        sudo apt update
        sudo apt install swi-prolog

    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Test
      timeout-minutes: 10
      run: make test

  test-parallel:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install swi-prolog
      run: |
        sudo apt-add-repository ppa:swi-prolog/stable
        sudo apt update
        sudo apt install swi-prolog

    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Test
      timeout-minutes: 10
      run: make test PARALLEL=1
